# Compress stage: Use Ubuntu as the base image for the compressed stage
FROM build AS multistaged
# Set the working directory in the container
WORKDIR /app

# Copy only the necessary files from the build stage
COPY --from=build /app .
Run rm /opt
    rm /bin
    

# Expose the required port for the application to work
EXPOSE 9000

# Set the entrypoint command
ENTRYPOINT ["python3", "app.py"]