apiVersion: v1
kind: Service
metadata:
  name: ai-image-classifier-service
spec:
  selector:
    app: ai-image-classifier
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort

