name: lab1

on:
  push:
    branches: [ "main" ]           # Trigger on push to the main branch
  pull_request:
    branches: [ "main" ]           # Trigger on pull request to main
  workflow_dispatch:               # Allow manual execution from GitHub UI

jobs:
  build-and-scan:
    runs-on: ubuntu-latest         # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Step 2: Set up Docker Buildx for advanced build support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

